version: "3"

services:
  samp:
    image: mrucznik/mrucznik-rp:v2.6
    build: .
    volumes:
      - ./scriptfiles:/samp/scriptfiles
      - ./logs:/samp/logs
    expose:
      - "7777"
    ports:
      - "7777:7777"
    environment:
      SAMP_DISCORD_BOT_TOKEN: NjA0NzIwMzk3NTk4MDY0NjUx.XTyEBw.NGrfO3u_0HdE2iUI60IQFQMY_6k
    networks:
      intranet:
        aliases:
          - samp
    depends_on:
      - mysqld
      # - migrations

  mysqld:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: samp
    expose:
      - "3306"
    networks:
      intranet:
        aliases:
          - mysqld

  # migrations:
  #   image: mysql_migration
  #   volumes:
  #     - ./migrations:/docker-entrypoint-migrations.d
  #   environment:
  #     MYSQL_HOST: mysqld
  #     MYSQL_DATABASE: samp
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     # TODO:
  #     # You can avoid repeating the environment variables using the env_file directive in your compose file 
  #     # to define the MySQL credentials in one place instead of two.
  #   networks:
  #     intranet:
  #       aliases:
  #         - migrations

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - intranet
    depends_on:
      - mysqld

networks:
  intranet:
    driver: bridge

volumes:
  my-datavolume:
  data: